---
title: '&nbsp;'
output: html_document
runtime: shiny_prerendered
banner: ''
description: 'An interactive dashboard to search for Useless AFL Stats'
images: []
menu: ''
---

```{r, context="setup", echo=F, warning=F, message=F}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(dplyr)
library(shiny)
library(ggplot2)
library(tidyr)
library(ggpubr)
library(DT)
```

```{r, context="data"}
weather_data <- readRDS("weather_data.rds")
team_names <- unique(weather_data$playing_for)
player_names <- unique(weather_data$full_name)
```

```{r, context='render'}
fluidPage(
  fluidRow(
    column(3,selectInput("team", "Select Team:", choices = team_names, selected = 'Richmond')),
  ),
  plotOutput("team_plot_out"),
  fluidRow(
    column(3,selectInput("player", "Select Player:", choices = player_names, selected = 'Ollie Wines 12155')),
  ),
  plotOutput("player_plot_out"),
)

# DT::dataTableOutput('afl_out_dt')

```

```{r, context='server'}
# output$afl_out_dt <- DT::renderDataTable({
#   DT::datatable(
#     weather_data %>% 
#       filter(
#         playing_for == input$team
#       ),
#     extensions = 'FixedHeader',
#     filter = 'top',
#     rownames = F,
#     options = list(
#       order = list(8, 'desc'),
#       fixedHeader = TRUE,
#       pageLength = 50
#     )
#   )
# })

output$team_plot_out <- renderPlot({
  clean_weather_data_team <- weather_data %>% 
    filter(
      playing_for == input$team
    ) %>% 
    group_by(season, round, weather_binary, stat_name) %>% 
    summarise(
      avg_value = mean(value),
      tot_value = sum(value),
      .groups = 'drop'
    ) %>% 
    drop_na()
  
  p_box_team <- ggboxplot(clean_weather_data_team, y = 'avg_value', x = 'weather_binary', fill = 'weather_binary',
                          add = 'jitter', add.params = list(alpha = 0.4)) +
    stat_compare_means(aes(label = paste0(..p.format..,..p.signif..)),
                       label.x = 1.3, label.y.npc = 0.95, hide.ns = T) +
    labs(y = '',
         x = '',
         title = paste0(input$team,' Stat per Game by Weather Type'),
         subtitle = "Each point represents the average stats of a single game, 2010-2021",
         caption = '@crow_data_sci, data: @fryzigg and #fitzRoy') +
    theme(
      legend.position = 'top',
      legend.title = element_blank()
    )
  
  p_box_team_facet <- facet(p_box_team, facet.by = 'stat_name', nrow = 2, scales = 'free_y')
  
  p_box_team_facet
})

output$player_plot_out <- renderPlot({
  clean_weather_data_player <- weather_data %>% 
    filter(
      full_name == input$player
    ) %>% 
    drop_na()
  
  p_box_player <- ggboxplot(clean_weather_data_player, y = 'value', x = 'weather_binary', fill = 'weather_binary',
                            add = 'jitter', add.params = list(alpha = 0.4)) +
    stat_compare_means(aes(label = paste0(..p.format..,..p.signif..)),
                       label.x = 1.3, label.y.npc = 0.95, hide.ns = T) +
    labs(y = '',
         x = '',
         title = gsub('[0-9]','',paste0(input$player, 'Stat per Game by Weather Type')),
         subtitle = "Each point represents the stats of a single game, 2010-2021",
         caption = '@crow_data_sci, data: @fryzigg and #fitzRoy') +
    theme(
      legend.position = 'top',
      legend.title = element_blank()
    )
  
  p_box_player_facet <- facet(p_box_player, facet.by = 'stat_name', nrow = 2, scales = 'free_y')
  
  p_box_player_facet
})

```

